# Generated by Django 4.2.7 on 2023-11-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tiles_folder', models.CharField(default='/media/uploads/projects/efteling', max_length=500)),
                ('center', models.CharField(default='0,0', max_length=200)),
                ('tiles_in_folders', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(upload_to='./uploads/thumbnails')),
                ('minzoom', models.IntegerField(default=0)),
                ('maxzoom', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon_type', models.CharField(choices=[('Pin', 'Pin Icon'), ('Area', 'Area Icon'), ('Accesibility', 'Accessibility Icon')], default='Pin', max_length=100)),
                ('icon', models.FileField(upload_to='./uploads/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('custom_map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.custommaps')),
            ],
        ),
        migrations.CreateModel(
            name='Pins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('pin_type', models.CharField(choices=[('Area Pin', 'Area Pin'), ('Detail Pin', 'Detail Pin')], default='Detail Pin', max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('description', models.TextField(null=True)),
                ('icon', models.CharField(default='icon.png', max_length=200)),
                ('poi_category', models.CharField(default='', max_length=200)),
                ('maxzoom', models.IntegerField(default=18)),
                ('minzoom', models.IntegerField(default=0)),
                ('bottom_link', models.CharField(max_length=250)),
                ('location_image', models.ImageField(default='default.png', upload_to='./uploads/thumbnails/pin_images/')),
                ('accesibility_features', models.JSONField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project')),
            ],
        ),
    ]
