# Generated by Django 4.2.7 on 2023-11-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommaps',
            name='tiles_folder',
            field=models.CharField(default='/media/uploads/projects/efteling', max_length=400),
        ),
    ]
