# Generated by Django 4.2.7 on 2023-12-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('pin_type', models.CharField(choices=[('Area Pin', 'Area Pin'), ('Detail Pin', 'Detail Pin')], default='Detail Pin', max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(default='Attraction', max_length=100)),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(max_length=100)),
                ('maxzoom', models.IntegerField(default=18)),
                ('minzoom', models.IntegerField(default=0)),
                ('bottom_link', models.CharField(max_length=250)),
                ('location_image', models.ImageField(default='default.png', upload_to='./uploads/thumbnails/pin_images/')),
                ('accesibility_features', models.JSONField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project')),
            ],
            options={
                'verbose_name_plural': 'Pins',
            },
        ),
    ]
