# Generated by Django 4.2.7 on 2023-11-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='project',
            name='tiles_folder',
            field=models.FilePathField(default='/media/uploads/projects/efteling'),
        ),
    ]
