# Generated by Django 4.2.7 on 2023-11-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_project_images_project_tiles_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tiles_folder', models.FilePathField(default='/media/uploads/projects/efteling')),
                ('center', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='./media/upload/thumbnails')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tiles_folder',
        ),
        migrations.AddField(
            model_name='point',
            name='latitue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project'),
        ),
        migrations.AlterField(
            model_name='icons',
            name='icon',
            field=models.FileField(upload_to='./media/uploads/icons/'),
        ),
        migrations.AlterField(
            model_name='point',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.icons'),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.custommaps'),
        ),
    ]
