# Generated by Django 4.2.7 on 2023-11-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_custommaps_remove_project_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='Pins',
        ),
        migrations.AlterField(
            model_name='custommaps',
            name='thumbnail',
            field=models.ImageField(upload_to='../media/uploads/thumbnails'),
        ),
    ]
