# Generated by Django 4.2.7 on 2023-12-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pincategory_active_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='active_icon',
            field=models.CharField(default='uploads/icons/axe_active.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pins',
            name='icon',
            field=models.CharField(max_length=1000),
        ),
    ]
