# Generated by Django 4.2.7 on 2023-12-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pins_active_icon_alter_pins_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommaps',
            name='bearing',
            field=models.IntegerField(default=0),
        ),
    ]
