# Generated by Django 4.2.7 on 2023-11-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_point_pins_alter_custommaps_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pins',
            old_name='latitue',
            new_name='latitude',
        ),
        migrations.RemoveField(
            model_name='pins',
            name='body',
        ),
        migrations.RemoveField(
            model_name='pins',
            name='minzoom',
        ),
        migrations.AddField(
            model_name='icons',
            name='icon_type',
            field=models.CharField(choices=[('Pin', 'Pin Icon'), ('Accesibility', 'Accessibility Icon')], default='Pin', max_length=100),
        ),
        migrations.AddField(
            model_name='pins',
            name='accesibility_features',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='pins',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pins',
            name='location_image',
            field=models.ImageField(default='default.png', upload_to='../media/uploads/thumbnails/pin_images/'),
        ),
    ]
