# Generated by Django 4.2.7 on 2023-11-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_latitue_pins_latitude_remove_pins_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommaps',
            name='maxzoom',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='custommaps',
            name='minzoom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='custommaps',
            name='center',
            field=models.CharField(default='0,0', max_length=200),
        ),
    ]
