# Generated by Django 4.2.7 on 2023-12-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_project_lang_alter_project_reading_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_lang',
            new_name='project_language',
        ),
    ]
