# Generated by Django 4.2.7 on 2023-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_custommaps_maxzoom_custommaps_minzoom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icons',
            name='icon',
            field=models.FileField(upload_to='../media/uploads/icons/'),
        ),
    ]
