# Generated by Django 4.2.7 on 2023-11-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_icons_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icons',
            name='icon',
            field=models.ImageField(upload_to='../media/uploads/icons/'),
        ),
    ]
