# Generated by Django 4.2.7 on 2023-12-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_project_project_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincategory',
            name='title_ar',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pincategory',
            name='title_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pincategory',
            name='title_he',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
