# Generated by Django 4.2.7 on 2023-11-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_icons_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='poi_category',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='pins',
            name='icon',
            field=models.CharField(default='icon.png'),
        ),
        migrations.AlterField(
            model_name='pins',
            name='location_image',
            field=models.ImageField(default='default.png', upload_to='./uploads/thumbnails/pin_images/'),
        ),
    ]
