# Generated by Django 4.2.7 on 2023-11-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pins_poi_category_alter_pins_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommaps',
            name='tiles_in_folders',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custommaps',
            name='thumbnail',
            field=models.ImageField(upload_to='./uploads/thumbnails'),
        ),
    ]
