# Generated by Django 4.2.7 on 2023-12-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pins_category_ar_pins_category_en_pins_category_he_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='more_info_link',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
