# Generated by Django 4.2.7 on 2023-11-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_custommaps_tiles_in_folders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='minzoom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pins',
            name='pin_type',
            field=models.CharField(choices=[('Area Pin', 'Area Pin'), ('Detail Pin', 'Detail Pin')], default='Area Pin', max_length=100),
        ),
        migrations.AlterField(
            model_name='icons',
            name='icon_type',
            field=models.CharField(choices=[('Pin', 'Pin Icon'), ('Area', 'Area Icon'), ('Accesibility', 'Accessibility Icon')], default='Pin', max_length=100),
        ),
    ]
