# Generated by Django 4.2.7 on 2023-12-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pins_more_info_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='more_info_link_ar',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='pins',
            name='more_info_link_en',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='pins',
            name='more_info_link_he',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
