# Generated by Django 4.2.7 on 2023-11-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pins_minzoom_pins_pin_type_alter_icons_icon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='pin_type',
            field=models.CharField(choices=[('Area Pin', 'Area Pin'), ('Detail Pin', 'Detail Pin')], default='Detail Pin', max_length=100),
        ),
    ]
