# Generated by Django 4.2.7 on 2023-12-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_pincategory_is_area_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='more_info_link',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='more_info_link_ar',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='more_info_link_en',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='more_info_link_he',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
