# Generated by Django 4.2.7 on 2023-12-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_pins_more_info_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='subcategory_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='subcategory_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='subcategory_he',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
