# Generated by Django 4.2.7 on 2023-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_pins_subcategory_alter_pins_subcategory_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommaps',
            name='is_osm_based_map',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_theme',
            field=models.TextField(default='""\n    --project-font:\'Poppins\', sans-serif !important;\n    --filter-bg-color:#5F6F52;\n    --icons-bg:#A9B388;\n    --infobox-bg:#FEFAE0;\n    --text-color:#B99470;\n    --filter-card-active:#5F6F52;\n', max_length='1000'),
        ),
    ]
