# Generated by Django 4.2.7 on 2023-12-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_project_project_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_theme',
            field=models.TextField(default="\n    --project-font:'Poppins', sans-serif !important;\n    --canvas-bg-color:#000000;\n    --area-text-color:#fffff;\n    --filter-bg-color:#5F6F52;\n    --icons-bg:#A9B388;\n    --infobox-bg:#FEFAE0;\n    --text-color:#B99470;\n    --filter-card-active:#5F6F52;\n", max_length=200),
        ),
    ]
