# Generated by Django 4.2.7 on 2023-12-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_project_project_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincategory',
            name='ranking_value',
            field=models.IntegerField(default=0),
        ),
    ]
