# Generated by Django 4.2.7 on 2023-12-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_custommaps_map_style_url_alter_project_project_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='INFOBOX_TYPES',
            field=models.CharField(choices=[('Default', 'Default'), ('Aside', 'Side Infobox')], default='Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='custommaps',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='description_he',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='pin_type',
            field=models.CharField(choices=[('Area Pin', 'Area Pin'), ('Detail Pin', 'Detail Pin'), ('Simple Icon', 'Simple Icon'), ('Simple Text', 'Simple Text')], default='Detail Pin', max_length=100),
        ),
    ]
