# Generated by Django 4.2.7 on 2023-12-24 13:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_project_infobox_types_alter_custommaps_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='is_simple_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custommaps',
            name='thumbnail',
            field=models.ImageField(upload_to='./uploads/thumbnails/custommaps/'),
        ),
        migrations.AlterField(
            model_name='pincategory',
            name='active_icon',
            field=models.FileField(default='uploads/icons/axe_active.png', upload_to=main.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='pincategory',
            name='icon',
            field=models.FileField(upload_to=main.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='pins',
            name='location_image',
            field=models.ImageField(default='default.png', upload_to=main.models.pin_file_name),
        ),
    ]
