# Generated by Django 4.2.7 on 2023-12-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_pins_is_simple_pin_alter_custommaps_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='INFOBOX_TYPES',
            new_name='infobox_style',
        ),
    ]
