# Generated by Django 4.2.7 on 2023-12-28 09:55

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_infobox_types_project_infobox_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincategory',
            name='is_simple_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pincategory',
            name='icon',
            field=models.FileField(default='uploads/icons/axe_active.png', upload_to=main.models.content_file_name),
        ),
    ]
