# Generated by Django 4.2.7 on 2023-12-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_pincategory_is_simple_icon_alter_pincategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommaps',
            name='tileSize',
            field=models.IntegerField(default=256),
        ),
    ]
