# Generated by Django 4.2.7 on 2024-01-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_custommaps_tilesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommaps',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
