# Generated by Django 4.2.7 on 2024-01-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_project_project_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pins',
            name='subtitle_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='subtitle_he',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
