# Generated by Django 4.2.7 on 2024-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_project_project_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommaps',
            name='mobile_minzoom',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_theme',
            field=models.TextField(default='\n    --project-font:Poppins, sans-serif !important;\n    --project-font-he:Poppins, sans-serif !important;\n    --project-font-ar:Poppins, sans-serif !important;\n    --simple-text-size:12;\n    --simple-text-offset:1;\n    --area-text-size:10;\n    --area-text-offset:3.2;\n    --simple-text-minzoom:14;\n    --simple-icon-minzoom:14;\n    --area-icon-minzoom:2;\n    --canvas-bg-color:#000000;\n    --area-text-color:#ffffff;\n    --simple-text-color:#000;\n    --circle-icon-color:#4D3929;\n    --circle-icon-stroke-color:#fff;\n\n    --filter-bg-color:#5F6F52;\n    --icons-bg:#A9B388;\n    --infobox-bg:#FEFAE0;\n    --infobox-text-color:#00ffff;\n    --infobox-title-font-size:21px;\n    --infobox-subtitle-font-size:18px;\n    --infobox-font-size:13px;\n    --filter-icon-size:30px;\n\n    --text-color:#B99470;\n    --filter-card-active:#5F6F52;\n    --filter-card-active-text-color:#00ff00;\n    --filter-card-line-color:#00ffff;\n\n    --accept-button-bg-color:#000;\n    --accept-button-text-color:#fff;\n    --close-button-bg-color:#fff;\n    --close-button-text-color:#f0f00f;\n', max_length=4100),
        ),
    ]
